### ISSUE TITLE
Turn bag

### ISSUE THREAD

**Issue by arty7731** [finalist736/seabotserver#1]
При уничтожении корабля result = 1

**Comment by finalist736** [comment]
еще не решил как определить, что корабль подбит полностью. на эту фичу высокий приоритет.

**Comment by finalist736** [comment]
новая версия сервера имеет реализацию этой проверки. нужны тесты!

**Comment by arty7731** [comment]
Уничтожение корабля происходит. Вот еще один баг [https://www.screencast.com/t/wzB5ExEGm](https://www.screencast.com/t/wzB5ExEGm), это при выигрыше приходит такой json и в документации написано opponent, а приходит ships.
