### ISSUE TITLE
Ошибки в отправленном джейсоне

### ISSUE THREAD

**Issue by RomanTymokhov** [finalist736/seabotserver#2]
Привет.
У меня с течением времени во время получения ответа от сервака, приходит джейсон с ошибками
![default](https://cloud.githubusercontent.com/assets/17049835/23330214/6660ff22-fb51-11e6-85cd-3d02851ad62c.png)
Чтобы это могло быть?

**Comment by RomanTymokhov** [comment]
Потом все таки приходит без ошибки.

**Comment by finalist736** [comment]
а ты зр ен пишешь на экран, что ты отправляешь на сервер. могли бы посмотреть изза чего ошибка

**Comment by RomanTymokhov** [comment]
Разобрался, нашел места, где не в свою очередь стреляю..
